services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dblog
      POSTGRES_USER: dblog
      POSTGRES_PASSWORD: dblog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
